"""
Centralised path constants for the Mental Health Intelligence project.

All other modules should import paths from here — never hardcode
directory paths inside application or notebook code.
"""
from __future__ import annotations

from pathlib import Path

# ============================================================
# Root anchors
# ============================================================

PROJECT_ROOT: Path = Path(__file__).resolve().parents[3]
SRC_DIR: Path = PROJECT_ROOT / "src"
SAMPLE_OUTPUTS_DIR: Path = PROJECT_ROOT / "docs" / "sample_outputs"

# ============================================================
# Data
# ============================================================

DATA_DIR: Path = PROJECT_ROOT / "data"
DATA_RAW_DIR: Path = DATA_DIR / "raw"
DATA_CLEAN_DIR: Path = DATA_DIR / "clean"

RAW_DATA_PATH: Path = DATA_RAW_DIR / "Mental Health Disorder Detection Dataset.csv"
DEFAULT_CLEAN_DATA_PATH: Path = DATA_CLEAN_DIR / "mental_health_detection_clean.csv"

# ============================================================
# Models
# ============================================================

MODELS_DIR: Path = PROJECT_ROOT / "models"

MODEL_CANDIDATES: dict[str, list[Path]] = {
    "LinearSVC Balanced": [
        MODELS_DIR / "best_classical_model.joblib",
        SRC_DIR / "model" / "best_classical_model.joblib",
    ],
    "Hybrid SVC": [
        MODELS_DIR / "hybrid_svc_model.joblib",
    ],
    "MentalBERT": [
        MODELS_DIR / "mentalbert_pipeline.joblib",
        MODELS_DIR / "mental_bert_pipeline.joblib",
        MODELS_DIR / "mentalbert_model.joblib",
    ],
    "BERT Base": [
        MODELS_DIR / "bert_base_pipeline.joblib",
        MODELS_DIR / "bert_pipeline.joblib",
        MODELS_DIR / "bert_model.joblib",
    ],
}

# ============================================================
# Reports & evaluation artifacts
# ============================================================

REPORTS_DIR: Path = PROJECT_ROOT / "reports"
CLASSICAL_REPORTS_DIR: Path = REPORTS_DIR / "tables" / "classical"
TRANSFORMER_REPORTS_DIR: Path = REPORTS_DIR / "transformers"
CLINICAL_TABLES_DIR: Path = REPORTS_DIR / "tables" / "clinical"

FINAL_TEST_METRICS_PATH: Path = CLASSICAL_REPORTS_DIR / "final_test_metrics.csv"
NESTED_CV_SUMMARY_PATH: Path = CLASSICAL_REPORTS_DIR / "nested_cv_summary.csv"
NORMAL_CV_SUMMARY_PATH: Path = CLASSICAL_REPORTS_DIR / "normal_cv_summary.csv"

# Phase 11: every benchmarked candidate (not just the champion), evaluated
# on the SAME held-out test set with the full rigor metric suite
# (f1_macro, recall_macro, critical_recall, mcc, brier_score, ece) --
# regenerated by every train.py run, so it stays current as new
# candidates (XGBoost/LightGBM now, embeddings/DistilBERT later) join the
# registry.
MODEL_COMPARISON_PATH: Path = CLASSICAL_REPORTS_DIR / "model_comparison.csv"
GLOBAL_CLINICAL_REVIEW_PATH: Path = CLINICAL_TABLES_DIR / "global_comparison_for_clinical_review.csv"

# ============================================================
# RAG knowledge base
# ============================================================

RAG_SOURCE_DIR: Path = PROJECT_ROOT / "rag_source"
RAG_INDEX_DIR: Path = PROJECT_ROOT / "faiss_index"

# ============================================================
# Domain constants
# ============================================================

CLASS_LABELS: list[str] = [
    "ADHD",
    "Anxiety",
    "Autism",
    "Bipolar",
    "BPD",
    "Depression",
    "Schizophrenia",
]

CRITICAL_LABELS: list[str] = ["Bipolar", "Schizophrenia"]
