"""
Enregistre le candidat DistilBERT déjà fine-tuné (voir
``distilbert_finetune.py``) dans le MLflow Model Registry comme le candidat
"staging" actuel — sur le même pied que tout champion classique/embedding
que ``train.py`` produit — afin que la porte existante et INCHANGÉE de
``promote.py`` (``f1_macro`` ET ``critical_recall`` ne doivent pas régresser vs. la
"production" actuelle) puisse décider s'il devient le nouveau modèle de production.

Pourquoi un script séparé plutôt que de brancher DistilBERT dans
``run_champion_stage`` : le fine-tuning n'est délibérément PAS exécuté à travers la
nested CV (voir la docstring de ``distilbert_finetune.py``) — il est entraîné une fois, hors
bande, directement sur la machine d'Ana. Ce script ne fait que les deux choses que
``run_champion_stage`` fait pour tout autre champion une fois l'entraînement
terminé : logger un run MLflow avec le modèle + les métriques, et l'aliaser "staging".
Décider effectivement de la promotion reste une étape séparée et explicite —
``python -m mental_health.train.promote`` — inchangée par ce script.

NOTE (autrefois une mise en garde, désormais résolue) : ``mental_health.api.model_loader``
et ``mental_health.api.main`` sont conscients du flavor — ils détectent si
le modèle aliasé "production" est un pipeline scikit-learn ou un pipeline
Transformers (via ``mlflow.models.get_model_info(...).flavors``) et se répartissent
en conséquence, donc un candidat DistilBERT promu ici EST servable via
le même contrat ``/predict`` qu'un modèle classique, sans changement
supplémentaire nécessaire.

Nécessite l'extra ``transformers`` (``pip install -e ".[transformers]"``)
— ``torch``/``transformers`` sont importés paresseusement, à l'intérieur de
``register_distilbert_candidate``, pas au niveau du module, afin que
``load_distilbert_metrics`` (et l'import de ce module) restent utilisables sans
cet extra volumineux installé — même convention que ``distilbert_finetune.py``.
"""
from __future__ import annotations

import logging
from pathlib import Path

import mlflow
import pandas as pd
from dotenv import load_dotenv

# Doit s'exécuter avant que l'import mlflow_config ci-dessous ne lise MLFLOW_TRACKING_URI /
# MLFLOW_ARTIFACT_ROOT depuis l'environnement — voir la docstring de
# mlflow_config.py (même convention que train.py / promote.py).
load_dotenv()

from mental_health.config.mlflow_config import (  # noqa: E402
    MLFLOW_ARTIFACT_ROOT,
    MLFLOW_EXPERIMENT_NAME,
    MLFLOW_REGISTERED_MODEL_NAME,
    MLFLOW_TRACKING_URI,
    STAGING_ALIAS,
)
from mental_health.config.paths import (  # noqa: E402
    DISTILBERT_METRICS_PATH,
    DISTILBERT_MODEL_DIR,
)

logger = logging.getLogger(__name__)

# Les métriques principales que tout candidat de ce projet rapporte (correspond
# aux colonnes que produisent à la fois evaluate_final_model et finetune_distilbert).
EXPECTED_METRICS = ["f1_macro", "recall_macro", "critical_recall", "mcc"]


def _get_or_create_experiment(name: str, artifact_location: str) -> str:
    """Récupère l'expérience par son nom, la crée (avec un emplacement d'artefact explicite) si elle n'existe pas."""
    experiment = mlflow.get_experiment_by_name(name)
    if experiment is not None:
        return experiment.experiment_id
    return mlflow.create_experiment(name, artifact_location=artifact_location)


def load_distilbert_metrics(metrics_path: Path = DISTILBERT_METRICS_PATH) -> dict:
    """
    Lit le CSV de métriques à une seule ligne écrit par ``distilbert_finetune.run()``
    et retourne uniquement les métriques principales, sous forme de simple dict — la même forme
    que retourne ``promote.get_metrics_for_version`` pour tout autre candidat.
    """
    df = pd.read_csv(metrics_path)
    if len(df) != 1:
        raise ValueError(
            f"Expected exactly one row in {metrics_path}, found {len(df)} — "
            "was this file edited or regenerated by something other than "
            "distilbert_finetune.run()?"
        )

    row = df.iloc[0]
    missing = [m for m in EXPECTED_METRICS if m not in row]
    if missing:
        raise ValueError(f"{metrics_path} is missing expected metric column(s): {missing}")

    return {metric: float(row[metric]) for metric in EXPECTED_METRICS}


def register_distilbert_candidate(
    model_dir: Path = DISTILBERT_MODEL_DIR,
    metrics_path: Path = DISTILBERT_METRICS_PATH,
) -> str:
    """
    Logue le modèle DistilBERT fine-tuné (depuis ``model_dir``) plus ses
    métriques (depuis ``metrics_path``) comme un seul run MLflow, l'enregistre sous
    ``MLFLOW_REGISTERED_MODEL_NAME``, et l'aliase "staging" — exactement
    comme ``run_champion_stage`` le fait pour tout champion
    classique/embedding. Retourne la chaîne de version enregistrée.

    Écrase quelle que soit la version actuellement aliasée "staging" — c'est
    le même comportement que tout autre run d'entraînement a déjà (voir
    la docstring de ``train.py``, point 5) : "staging" signifie toujours "le
    candidat entraîné le plus récemment, pas encore promu", jamais "le meilleur
    vu jusqu'ici".
    """
    import torch  # noqa: F401 -- importé pour son effet de bord : une ImportError claire ici si l'extra transformers n'est pas installé, avant de faire tout travail MLflow
    from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline

    metrics = load_distilbert_metrics(metrics_path)

    mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
    experiment_id = _get_or_create_experiment(MLFLOW_EXPERIMENT_NAME, MLFLOW_ARTIFACT_ROOT)
    mlflow.set_experiment(experiment_id=experiment_id)

    tokenizer = AutoTokenizer.from_pretrained(str(model_dir))
    model = AutoModelForSequenceClassification.from_pretrained(str(model_dir))
    # top_k=None et truncation=True sont tous deux définis ici pour un pipeline
    # initial propre, mais rien ne garantit que ni l'un ni l'autre survivent à l'aller-retour
    # log/load de MLflow -- chaque appelant (main.py, drift_check.py) passe à nouveau les
    # deux explicitement au moment de l'appel. Voir la docstring de
    # _predict_with_transformers_model dans main.py pour la raison (un texte non tronqué
    # dépassant la limite de 512 tokens du modèle fait planter les position
    # embeddings de PyTorch au lieu d'échouer proprement).
    text_classification_pipeline = pipeline(
        "text-classification", model=model, tokenizer=tokenizer, top_k=None, truncation=True
    )

    with mlflow.start_run(run_name="distilbert_finetuned_candidate"):
        mlflow.log_param("stage", "distilbert_candidate")
        mlflow.log_param("champion_model", "DistilBERT_finetuned")
        mlflow.log_param("text_variant", "raw")
        mlflow.log_param("base_model", getattr(model.config, "_name_or_path", "distilbert-base-uncased"))
        mlflow.log_param("num_labels", model.config.num_labels)
        # Non benchmarké via nested CV (voir la docstring de ce module) --
        # loggé explicitement pour que le run de ce candidat ne soit jamais confondu
        # avec un candidat étant passé par la même rigueur que tout candidat
        # classique/embedding dans run_benchmark_stage.
        mlflow.log_param("nested_cv_benchmarked", False)

        for name, value in metrics.items():
            mlflow.log_metric(name, value)

        model_info = mlflow.transformers.log_model(
            transformers_model=text_classification_pipeline,
            name="model",
            registered_model_name=MLFLOW_REGISTERED_MODEL_NAME,
            task="text-classification",
        )

        client = mlflow.MlflowClient()
        client.set_registered_model_alias(
            MLFLOW_REGISTERED_MODEL_NAME, STAGING_ALIAS, model_info.registered_model_version
        )

        logger.info(
            "Registered DistilBERT_finetuned as '%s' v%s, aliased '%s' -- metrics: %s",
            MLFLOW_REGISTERED_MODEL_NAME, model_info.registered_model_version, STAGING_ALIAS, metrics,
        )

    return model_info.registered_model_version


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    registered_version = register_distilbert_candidate()
    logger.info(
        "Done. '%s' v%s is now aliased '%s'. Run `python -m mental_health.train.promote` "
        "to decide whether it becomes 'production' -- the API's model_loader/main.py are "
        "flavor-aware, so a promoted DistilBERT version is servable through /predict.",
        MLFLOW_REGISTERED_MODEL_NAME, registered_version, STAGING_ALIAS,
    )
