"""
Register the already fine-tuned DistilBERT candidate (see
``distilbert_finetune.py``) in the MLflow Model Registry as the current
"staging" candidate — on the same footing as every classical/embedding
champion ``train.py`` produces — so ``promote.py``'s existing, UNCHANGED
gate (``f1_macro`` AND ``critical_recall`` must not regress vs. current
"production") can decide whether it becomes the new production model.

Why a separate script instead of wiring DistilBERT into
``run_champion_stage``: fine-tuning is deliberately NOT run through nested
CV (see ``distilbert_finetune.py``'s docstring) — it is trained once, out
of band, directly on Ana's machine. This script only does the two things
``run_champion_stage`` does for every other champion once training is
done: log an MLflow run with the model + metrics, and alias it "staging".
Actually deciding promotion is still a separate, explicit step —
``python -m mental_health.train.promote`` — unchanged by this script.

NOTE (previously a caveat, now resolved): ``mental_health.api.model_loader``
and ``mental_health.api.main`` are flavor-aware — they detect whether the
"production"-aliased model is a scikit-learn pipeline or a Transformers
pipeline (via ``mlflow.models.get_model_info(...).flavors``) and dispatch
accordingly, so a DistilBERT candidate promoted here IS servable through
the same ``/predict`` contract as a classical model, no further change
needed.

Requires the ``transformers`` extra (``pip install -e ".[transformers]"``)
— ``torch``/``transformers`` are imported lazily, inside
``register_distilbert_candidate``, not at module level, so
``load_distilbert_metrics`` (and this module's import) stay usable without
that heavy extra installed — same convention as ``distilbert_finetune.py``.
"""
from __future__ import annotations

import logging
from pathlib import Path

import mlflow
import pandas as pd
from dotenv import load_dotenv

# Must run before the mlflow_config import below reads MLFLOW_TRACKING_URI /
# MLFLOW_ARTIFACT_ROOT from the environment — see mlflow_config.py's
# docstring (same convention as train.py / promote.py).
load_dotenv()

from mental_health.config.mlflow_config import (  # noqa: E402
    MLFLOW_ARTIFACT_ROOT,
    MLFLOW_EXPERIMENT_NAME,
    MLFLOW_REGISTERED_MODEL_NAME,
    MLFLOW_TRACKING_URI,
    STAGING_ALIAS,
)
from mental_health.config.paths import (  # noqa: E402
    DISTILBERT_METRICS_PATH,
    DISTILBERT_MODEL_DIR,
)

logger = logging.getLogger(__name__)

# The headline metrics every candidate in this project reports (matches
# the columns evaluate_final_model / finetune_distilbert both produce).
EXPECTED_METRICS = ["f1_macro", "recall_macro", "critical_recall", "mcc"]


def _get_or_create_experiment(name: str, artifact_location: str) -> str:
    """Get the experiment by name, creating it (with an explicit artifact location) if missing."""
    experiment = mlflow.get_experiment_by_name(name)
    if experiment is not None:
        return experiment.experiment_id
    return mlflow.create_experiment(name, artifact_location=artifact_location)


def load_distilbert_metrics(metrics_path: Path = DISTILBERT_METRICS_PATH) -> dict:
    """
    Read the single-row metrics CSV written by ``distilbert_finetune.run()``
    and return just the headline metrics, as a plain dict — the same shape
    ``promote.get_metrics_for_version`` returns for any other candidate.
    """
    df = pd.read_csv(metrics_path)
    if len(df) != 1:
        raise ValueError(
            f"Expected exactly one row in {metrics_path}, found {len(df)} — "
            "was this file edited or regenerated by something other than "
            "distilbert_finetune.run()?"
        )

    row = df.iloc[0]
    missing = [m for m in EXPECTED_METRICS if m not in row]
    if missing:
        raise ValueError(f"{metrics_path} is missing expected metric column(s): {missing}")

    return {metric: float(row[metric]) for metric in EXPECTED_METRICS}


def register_distilbert_candidate(
    model_dir: Path = DISTILBERT_MODEL_DIR,
    metrics_path: Path = DISTILBERT_METRICS_PATH,
) -> str:
    """
    Log the fine-tuned DistilBERT model (from ``model_dir``) plus its
    metrics (from ``metrics_path``) as one MLflow run, register it under
    ``MLFLOW_REGISTERED_MODEL_NAME``, and alias it "staging" — exactly
    like ``run_champion_stage`` does for every classical/embedding
    champion. Returns the registered version string.

    Overwrites whichever version is currently aliased "staging" — this is
    the same behaviour every other training run already has (see
    ``train.py``'s docstring, point 5): "staging" always means "the most
    recently trained candidate, not yet promoted", never "the best one
    seen so far".
    """
    import torch  # noqa: F401 -- imported for its side effect: a clear ImportError here if the transformers extra isn't installed, before doing any MLflow work
    from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline

    metrics = load_distilbert_metrics(metrics_path)

    mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
    experiment_id = _get_or_create_experiment(MLFLOW_EXPERIMENT_NAME, MLFLOW_ARTIFACT_ROOT)
    mlflow.set_experiment(experiment_id=experiment_id)

    tokenizer = AutoTokenizer.from_pretrained(str(model_dir))
    model = AutoModelForSequenceClassification.from_pretrained(str(model_dir))
    # top_k=None and truncation=True are both set here for a clean initial
    # pipeline, but neither is guaranteed to survive the MLflow log/load
    # round-trip -- every caller (main.py, drift_check.py) passes both
    # explicitly again at call time. See main.py's
    # _predict_with_transformers_model docstring for why (an untruncated
    # text past the model's 512-token limit crashes PyTorch's position
    # embeddings instead of failing gracefully).
    text_classification_pipeline = pipeline(
        "text-classification", model=model, tokenizer=tokenizer, top_k=None, truncation=True
    )

    with mlflow.start_run(run_name="distilbert_finetuned_candidate"):
        mlflow.log_param("stage", "distilbert_candidate")
        mlflow.log_param("champion_model", "DistilBERT_finetuned")
        mlflow.log_param("text_variant", "raw")
        mlflow.log_param("base_model", getattr(model.config, "_name_or_path", "distilbert-base-uncased"))
        mlflow.log_param("num_labels", model.config.num_labels)
        # Not benchmarked through nested CV (see this module's docstring) --
        # logged explicitly so this candidate's run is never mistaken for
        # one that went through the same rigor as every classical/embedding
        # candidate in run_benchmark_stage.
        mlflow.log_param("nested_cv_benchmarked", False)

        for name, value in metrics.items():
            mlflow.log_metric(name, value)

        model_info = mlflow.transformers.log_model(
            transformers_model=text_classification_pipeline,
            name="model",
            registered_model_name=MLFLOW_REGISTERED_MODEL_NAME,
            task="text-classification",
        )

        client = mlflow.MlflowClient()
        client.set_registered_model_alias(
            MLFLOW_REGISTERED_MODEL_NAME, STAGING_ALIAS, model_info.registered_model_version
        )

        logger.info(
            "Registered DistilBERT_finetuned as '%s' v%s, aliased '%s' -- metrics: %s",
            MLFLOW_REGISTERED_MODEL_NAME, model_info.registered_model_version, STAGING_ALIAS, metrics,
        )

    return model_info.registered_model_version


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    registered_version = register_distilbert_candidate()
    logger.info(
        "Done. '%s' v%s is now aliased '%s'. Run `python -m mental_health.train.promote` "
        "to decide whether it becomes 'production' -- the API's model_loader/main.py are "
        "flavor-aware, so a promoted DistilBERT version is servable through /predict.",
        MLFLOW_REGISTERED_MODEL_NAME, registered_version, STAGING_ALIAS,
    )
